name: 'portfolio'
services:
  web:
    container_name: portfolio
    build: 
      context: ./
      target: base
    image: portfolio
    environment:
      NODE_ENV: development
    command: npm run dev
    ports:
      - '80:3000'
    
    volumes:
      - '.:/app'
      - /app/node_modules