import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
		<nav className="flex shadow-md min-h-16 items-center space-x-3 px-8">
			<Link href="/">Home</Link>
			<Link href="/todo">To Do</Link>
			<Link href="/shapes">Shapes</Link>

		</nav>
		<main className="px-8 py-2">
        	{children}
		</main>
      </body>
    </html>
  );
}
