import type { Metadata } from 'next';
import localFont from 'next/font/local';
import NavigationEvents from '../components/NavigationEvents';
import { Suspense } from 'react';
import Loading from '../loading';

// const geistSans = localFont({
//     src: './fonts/GeistVF.woff',
//     variable: '--font-geist-sans',
//     weight: '100 900',
// });
// const geistMono = localFont({
//     src: './fonts/GeistMonoVF.woff',
//     variable: '--font-geist-mono',
//     weight: '100 900',
// });

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function BlogLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ id: string }>;
}>) {
    // const pathname = usePathname();

    // const { id } = await params;
    // if (!id) {
    //     redirect('/');
    // }
    return (
        <div className="text-neutral-50 px-64 text-center">
            {/* <Suspense fallback={<Loading />}>
                <NavigationEvents />
            </Suspense> */}
            {children}
        </div>
    );
}
